//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracySecretTool.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTrain_Station
    {
        public int ID { get; set; }
        public string FirstLetter { get; set; }
        public string StationName { get; set; }
        public string FullLetter { get; set; }
        public string StationCode { get; set; }
        public int RowNo { get; set; }
    }
}
